[workspace]
resolver = "2"
members = [
    ".",
    "examples/any",
    "examples/postgres",
    "examples/sqlite",
    "examples/redis",
    "examples/surrealdb",
    "examples/middleware_layer",
    "examples/rest_test",
]

[package]
name = "axum_session"
version = "0.11.1"
authors = ["Andrew Wheeler <genusistimelord@gmail.com>"]
description = "📝 Session management layer for axum that supports HTTP and Rest."
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/axum_session"
keywords = ["Axum", "Tower", "SQLx", "Session", "surrealdb"]
repository = "https://github.com/AscendingCreations/AxumSession"

[features]
default = ["postgres-rustls"]

key-store = ["fastbloom-rs"]
sqlite-rustls = ["sqlx/sqlite", "sqlx/tls-rustls"]
sqlite-native = ["sqlx/sqlite", "sqlx/tls-native-tls"]
postgres-rustls = ["sqlx/postgres", "sqlx/tls-rustls"]
postgres-native = ["sqlx/postgres", "sqlx/tls-native-tls"]
mysql-rustls = ["sqlx/mysql", "sqlx/tls-rustls"]
mysql-native = ["sqlx/mysql", "sqlx/tls-native-tls"]
redis-db = ["redis_pool", "redis"]
redis-clusterdb = ["redis_pool/cluster", "redis/cluster-async"]
surreal = ["dep:surrealdb"]
mongo = ["mongodb"]
rest_mode = []
advanced = []

[dependencies]
axum-core = { version = "0.4.0" }
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
chrono = { version = "0.4.31", default-features = false, features = [
    "clock",
    "serde",
] }
tokio = { version = "1.34.0", features = ["full"] }
async-trait = "0.1.74"
tracing = "0.1.40"
thiserror = "1.0.50"
http-body = "1.0.0"
uuid = { version = "1.6.1", features = ["serde", "v4"] }
http = "1.0.0"
tower-layer = "0.3.2"
tower-service = "0.3.2"
sqlx = { version = "0.7.3", default-features = false, features = [
    "runtime-tokio",
    "chrono",
    "uuid",
], optional = true }
cookie = { version = "0.18.0", features = ["percent-encode", "private"] }
futures = "0.3.29"
bytes = "1.5.0"
dashmap = "5.5.3"
redis_pool = { version = "0.3.0", optional = true }
redis = { version = "0.24.0", features = [
    "aio",
    "tokio-comp",
], optional = true }
surrealdb = { git = "https://github.com/surrealdb/surrealdb.git", tag = "v1.1.0-beta.2", optional = true  }
aes-gcm = { version = "0.10.3" }
base64 = { version = "0.21.5" }
rand = { version = "0.8.5" }
fastbloom-rs = { version = "0.5.7", optional = true }
mongodb = { version = "2.7.1", optional = true }

[dev-dependencies]
axum = { version = "0.7.1", features = ["macros"] }
hyper = "1.0.1"
tower = "0.4.13"
log = { version = "0.4.20", default-features = false }
http-body-util = "0.1.0"

[package.metadata.docs.rs]
features = [
    "sqlite-rustls",
    "mysql-rustls",
    "redis-db",
    "surreal",
    "key-store",
    "advanced",
]
rustdoc-args = ["--document-private-items"]
